# Generated by Django 3.0.3 on 2020-02-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='GitHubPrefix',
            field=models.CharField(default='AssignmentName', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='GitHubPrefix',
            field=models.CharField(default='CourseName', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempusers',
            name='Firstname',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempusers',
            name='Lastname',
            field=models.CharField(default='Doe', max_length=50),
            preserve_default=False,
        ),
    ]
