# Generated by Django 3.0.3 on 2020-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0002_auto_20200225_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='SolutionLink',
            field=models.CharField(max_length=255),
        ),
    ]
