# Generated by Django 3.0.3 on 2020-02-28 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0003_auto_20200228_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempusers',
            name='Password',
        ),
        migrations.AddField(
            model_name='tempusers',
            name='User',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ideal_classroom.AuthUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.AuthUser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.AuthUser'),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('SchoolID', models.CharField(max_length=20)),
                ('GitHubUsername', models.CharField(max_length=255)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ideal_classroom.AuthUser')),
            ],
        ),
    ]
