# Generated by Django 3.0.3 on 2020-02-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0004_auto_20200228_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempusers',
            name='User',
        ),
        migrations.AlterField(
            model_name='course',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.TempUsers'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.TempUsers'),
        ),
    ]
