# Generated by Django 3.0.3 on 2020-02-29 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0005_auto_20200228_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.AuthUser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.AuthUser'),
        ),
    ]
