# Generated by Django 3.0.3 on 2020-02-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0006_auto_20200228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempusers',
            name='Password',
            field=models.CharField(default='Password', max_length=50),
            preserve_default=False,
        ),
    ]
