# Generated by Django 3.0.3 on 2020-02-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0007_tempusers_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
