# Generated by Django 3.0.3 on 2020-02-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0008_delete_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('SchoolID', models.CharField(max_length=20)),
                ('GitHubUsername', models.CharField(max_length=255)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ideal_classroom.AuthUser')),
            ],
        ),
    ]
