# Generated by Django 3.0.3 on 2020-02-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0009_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUsers',
        ),
    ]
