# Generated by Django 3.0.3 on 2020-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0011_auto_20200306_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
