# Generated by Django 3.0.3 on 2020-03-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0012_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ShowSolutionOnDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
