# Generated by Django 3.0.3 on 2020-03-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0013_auto_20200310_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='isTeacher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
