# Generated by Django 3.0.3 on 2020-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0014_userdetail_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
