# Generated by Django 3.0.3 on 2020-03-12 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0015_assignment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Password',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
