# Generated by Django 3.0.3 on 2020-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0016_auto_20200312_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Slug',
            field=models.SlugField(unique=True),
        ),
    ]
