# Generated by Django 3.0.3 on 2020-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0017_auto_20200312_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='SubmittedOn',
            field=models.DateTimeField(),
        ),
    ]
