# Generated by Django 3.0.3 on 2020-04-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_classroom', '0018_auto_20200326_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hasRun',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
