# Generated by Django 3.0.3 on 2020-02-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'managed': False},
        ),
    ]
