# Generated by Django 3.0.3 on 2020-02-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200216_2155'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
