# Generated by Django 3.0.3 on 2020-02-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200216_2201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hellotest',
            table='test',
        ),
    ]
