# Generated by Django 3.0.3 on 2020-02-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200216_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='HelloTest',
        ),
    ]
