# Generated by Django 3.0.3 on 2020-02-21 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20200220_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='InstructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.TempUsers'),
        ),
    ]
