# Generated by Django 3.0.3 on 2020-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200220_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ShowSolutionOnDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='SolutionLink',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Comments',
            field=models.TextField(blank=True),
        ),
    ]
